language: cpp
compiler: gcc
sudo: required
addons:
  apt:
    sources:
      - boost-latest
    packages:
      - libboost-system1.55-dev
      - libboost-chrono1.55-dev
      - libboost-timer1.55-dev
script: 
  - mkdir build && cd build
  - cmake ..
  - make
  - sudo make install
  - cd ../example && mkdir build && cd build
  - cmake ..
  - make 
