language: cpp
compiler: gcc
addons:
  apt:
    sources:
      - boost-latest
    packages:
      - libboost-system1.55-dev
      - libboost-chrono1.55-dev
      - libboost-timer1.55-dev
script: 
  - mkdir build
  - cd build
  - cmake ..
  - make 
